sqlite3 AuctionBase.db < create.sql
sqlite3 AuctionBase.db < load.txt
sqlite3 AuctionBase.db < constraints_verify.sql
sqlite3 AuctionBase.db < trigger8_add.sql
sqlite3 AuctionBase.db < trigger9_add.sql
sqlite3 AuctionBase.db < trigger11_add.sql
sqlite3 AuctionBase.db < trigger13_add.sql
sqlite3 AuctionBase.db < trigger14_add.sql
sqlite3 AuctionBase.db < trigger15_add.sql
sqlite3 AuctionBase.db < trigger16_add.sql
